### ISSUE TITLE
DODatabaseCluster `writeConnectionSecretToRef` won't create secret

### ISSUE THREAD

**Issue by gcavalcante8808** [crossplane-contrib/provider-digitalocean#33]
### How can we reproduce it?

After the provider configuration, I just applied the following spec:

```
apiVersion: database.do.crossplane.io/v1alpha1
kind: DODatabaseCluster
metadata:
  name: backstage-io
spec:
  forProvider:
    engine: pg
    version: "13"
    numNodes: 1
    size: db-s-1vcpu-1gb
    region: nyc1
    tags:
      - "crossplane"
  providerConfigRef:
    name: digitalocean
  writeConnectionSecretToRef:
    name: backstage-db-conn
    namespace: backstage-io
```

Which created the DO DatabaseCluster correctly, but doesn't created the secret with the resource credentials.

I checked and the resource was ready and synced and the namespace exists.

### What environment did it happen in?

CrossPlane: 1.6.3
DoProvider: v0.1.0

**Comment by ADustyOldMuffin** [comment]
Hello, thanks for creating this! Seems like it was glanced over when creating these resources. I'll get right on adding this!

**Comment by Lp-Francois** [comment]
Hello, following the documentation I can still see this error with the latest helm chart v1.10.1

```yaml
---
apiVersion: database.do.crossplane.io/v1alpha1
kind: DODatabaseCluster
metadata:
  name: redis-test-to-be-deleted
spec:
  forProvider:
    engine: redis
    version: "7"
    numNodes: 1
    size: db-s-1vcpu-1gb
    region: fra1
    tags:
      - "from-crossplane"
      - "redis"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: redis-test
  providerConfigRef:
    name: do-provider-config
```

I can see the database is created in the DO UI, and the resource is Sync & Ready, but no secret redis-test is created in any namespace.
