### ISSUE TITLE
Kubernetes cluster creation should also create a secret to access the newly created cluster

### ISSUE THREAD

**Issue by antevens** [crossplane-contrib/provider-digitalocean#57]
I asked around in the Slack channel about how to access newly created clusters and got the following answer for the AWS provider, I presume it would be good practise to implement something similar for the Digital Ocean provider.

[Slack Thread](https://crossplane.slack.com/archives/C01718T2476/p1649262365257779)

> The Cluster resource in provider-aws will create a secret with the credentials, and you can create a ProviderConfig for kubernetes which references that secret

```
- name: kubernetes_provider_config
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      spec:
        credentials:
          source: Secret
          secretRef:
            namespace: crossplane-system
            key: kubeconfig
    patches:
    - type: FromCompositeFieldPath
      transforms:
      - string:
          fmt: "%s-cluster"
          type: Format
        type: string
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: spec.credentials.secretRef.name
    - type: FromCompositeFieldPath
      transforms:
      - string:
          fmt: "%s-cluster"
          type: Format
        type: string
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.name
    readinessChecks:
    - type: None
```
