### ISSUE TITLE
droplet CR create multiple droplet

### ISSUE THREAD

**Issue by tuxtof** [crossplane-contrib/provider-digitalocean#58]
### What happened?

I try to create a single droplet CR and it never become ready and create me multiple Droplets on my DO account

![Screenshot 2022-06-11 at 14 54 53](https://user-images.githubusercontent.com/180613/173188849-b246a298-2177-4077-aadc-18df01fcec08.png)

### How can we reproduce it?
I reproduce it multiple time

with the following CR

```
apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: example
  annotations:
    crossplane.io/external-name: crossplane-droplet
spec:
  forProvider:
    region: ams3
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
  providerConfigRef:
    name: do-example
```

### What environment did it happen in?
Crossplane version: crossplane-1.8.1
Kubernetes: v1.21.8
DO Provider 0.1.0
