### ISSUE TITLE
Droplet: Add support for 'vpc_uuid'

### ISSUE THREAD

**Issue by jkpe** [crossplane-contrib/provider-digitalocean#72]
### What problem are you facing?
The '[DOKS-Egress-Gateway](https://github.com/digitalocean/container-blueprints/tree/main/DOKS-Egress-Gateway)'  requires us to [deploy](https://github.com/digitalocean/container-blueprints/tree/main/DOKS-Egress-Gateway#configuring-the-digitalocean-provider) a Droplet in the same VPC as our K8s cluster. It would be great if we could specify the VPC in the manifest and update the instructions so that our Droplet is deployed to the same VPC.

### How could Crossplane help solve your problem?
I am imagining something like this:

```
apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: egress-gw-nyc1
spec:
  forProvider:
    region: nyc1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
    vpc_uuid: "4bxx25e-c52e-4578-93a7-01xx1ee927xx"
```
